server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - UserServiceFilter
        - id: business-service
          uri: lb://BUSINESS-SERVICE
          predicates:
            - Path=/business/**
      default-filters:
        - name: LogFilter # 필터 컴포넌트의 클래스 명
          args:
            message: Hello LogFilter